---
title: "spread and gather"
author: "JP"
date: "Aug 10, 2017"
output: github_document
---

```{r}
library(tidyverse)
```

## gather and spread examples
```{r}
# create some data to spread and gather
mydata <- tribble(
  ~group_a, ~group_b, ~group_c, ~group_d, 
  21,       14,       10,       23,
  24,       20,       12,       35,
  34,       45,       34,       14
)

mydata

# Tidy up the data
mydata_gathered <- 
  mydata %>% 
  mutate(row = row_number()) %>% # rownumber is key for later spread b/c you
  # need a variable that uniquely identifyies observations
  gather(
    group_a:group_d, # old variables to gather
    key = group,     # new variable whose values will be old variable names
    value = score    # new variable whose valies will be old variable values
  ) 

mydata_gathered
  
# demo a spread
mydata_spread <- 
  mydata_gathered %>% 
  spread(key = group, value = score)

mydata_spread
```

"row number `spread()`" soln from [link](https://stackoverflow.com/questions/25960394/spread-with-data-frame-tibble-with-duplicate-identifiers).

`convert = TRUE` will produce variables of mixed types for `spread()` and detect types for `gather()`.

```{r}
stocks <- tibble(
  year   = c(2015, 2015, 2016, 2016),
  half  = c(   1,    2,     1,    2),
  return = c(1.88, 0.59, 0.92, 0.17)
)

stocks %>% 
  spread(
    key = year, 
    value = return) 

stocks %>% 
  spread(key = year, value = return) %>% 
  gather(key = year, value = return, `2015`:`2016`, convert = TRUE) %>% 
  select(year, half, return)
```



